#!/bin/bash

set -euo pipefail
eval "$(ucr shell)"

# get numberical user and group id of the kopano user
if id kopano >/dev/null 2>&1; then
	KOPANOUID=$(id -u kopano)
	KOPANOGID=$(id -g kopano)
else
	KOPANOUID=$(id -u nobody)
	KOPANOGID=$(id -g nobody)
fi

mkdir -p /etc/kopano/

# create encryption key if not already present
if [ ! -f /etc/kopano/konnectd-encryption.key ]; then
	echo "creating new encryption key"
	openssl rand -out /etc/kopano/konnectd-encryption.key 32
fi

# create token signing key if not already present
if [ ! -f /etc/kopano/konnectd-tokens-signing-key.pem ]; then
	echo "creating new token signing key"
	openssl genpkey -algorithm RSA -out /etc/kopano/konnectd-tokens-signing-key.pem -pkeyopt rsa_keygen_bits:4096
fi
chown $KOPANOUID:$KOPANOGID /etc/kopano/konnectd-tokens-signing-key.pem

if [ ! -f /etc/kopano/identifier-registration.yaml ]; then
	echo "creating template client registration"
	cat <<-EOF >"/etc/kopano/identifier-registration.yaml"
---

# Konnect needs to be restarted for changes to take effect.
# OpenID Connect client registry.
clients:
#  - id: playground.js
#    name: OIDC Playground
#    application_type: web
#    redirect_uris:
#       - https://my-host:8509/

#  - id: playground-trusted.js
#    name: Trusted OIDC Playground
#    trusted: yes
#    application_type: web
#    redirect_uris:
#       - https://my-host:8509/

#  - id: playground-trusted.js
#    name: Trusted Insecure OIDC Playground
#    trusted: yes
#    application_type: web
#    insecure: yes

#  - id: first
#    secret: lala
#    application_type: native
#    redirect_uris:
#      - my://app

#  - id: second
#    secret: lulu
#    application_type: native
#    redirect_uris:
#      - http://localhost
EOF
fi

kopanoversion=$(dpkg-query --showformat='${Version}' --show kopano-server)

# starting with the Kopano 8.7 release (but already available in previous nightly builds that are tagged 8.6.81) Kopano Konnect does not rely on the unix socket anymore to establish an authenticated connection. Instead Kopano Groupware Core is configured to make handle SSO requests from Konnect
if $(dpkg --compare-versions $kopanoversion "gt" "8.6.81"); then
        echo "Installation with Kopano Groupware Core 8.7 detected"
	echo "setting process of container to read-only"
	ucr set \
		appcenter/apps/kopano-konnect/docker/params="--read-only" \
		kopano/cfg/server/enable_sso="yes" \
		kopano/cfg/server/kcoidc_issuer_identifier="https://${hostname}.${domainname}"
	systemctl restart kopano-server
else
        echo "Previous version to Kopano Groupware Core 8.7 detected"
	echo "setting process of container to the id of the kopano or nobody user"
	ucr set appcenter/apps/kopano-konnect/docker/params="--read-only --user=$KOPANOUID:$KOPANOGID"
fi
