#!/bin/bash

. /usr/share/univention-lib/all.sh

ucs_parseCredentials "$@"
binduser="${binddn#uid=}"
binduser="${binduser%%,*}"
while [ $# -ge 1 ]; do
	case "$1" in
		--error-file)
		error_file="$2"
		shift 2 || die "Missing argument to --error-file"
		;;
	*)
		shift
		;;
	esac
done

for app in kopano-core kopano-webapp z-push-kopano; do
	if ! univention-app info | grep "Installed:" | grep -q "$app="; then
		univention-app install --pwdfile "$bindpwdfile" --username "$binduser" --noninteractive $app 2>$error_file
		test $? -eq 0 || exit 1
	fi
done
