#!/bin/bash

set -x

VERSION=1
SERVICE="Kopano-Api"

. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-appcenter/joinscripthelper.sh
. /usr/share/univention-lib/ldap.sh
. /usr/share/univention-lib/base.sh

joinscript_init
eval "$(ucr shell)"

CONFIG="$(joinscript_container_file /etc/univention/base.conf)"

ucs_addServiceToLocalhost "${SERVICE}" "$@"

# TODO create vhost for kopano-api

#a2enmod rewrite proxy proxy_http

#invoke-rc.d apache2 reload

joinscript_save_current_version
exit 0
