#!/bin/bash

eval "$(ucr shell)"

update_env_file () {
    varname="$1"
    varvalue="$2"
    if ! grep -q "$varname" ./.env; then
        echo "$varname=$varvalue" >> ./.env
    else
        sed -i "/$varname/c $varname=$varvalue" ./.env
    fi
}

cd /var/lib/univention-appcenter/apps/kopano-meet/compose
touch .env

# ask if running with self signed (untrusted) certificates
update_env_file INSECURE $(ucr get kopano/docker/INSECURE)

update_env_file GRID_WEBAPP $(ucr get kopano/docker/GRID_WEBAPP)

update_env_file TURN_USER $(ucr get kopano/docker/TURN_USER)
update_env_file TURN_PASSWORD $(ucr get kopano/docker/TURN_PASSWORD)

update_env_file MEET_GUEST $(ucr get kopano/docker/MEET_GUEST)
update_env_file MEET_GUEST_REGEXP $(ucr get kopano/docker/MEET_GUEST_REGEXP)

if [ "$1" = "settings" ]; then
    docker-compose up -d
fi