#!/bin/bash

eval "$(ucr shell)"

update_env_file () {
    varname="$1"
    varvalue="$2"
    if ! grep -q "$varname" ./.env; then
        echo "$varname=$varvalue" >> ./.env
    else
        sed -i "/$varname/c $varname=$varvalue" ./.env
    fi
}

cd /var/lib/univention-appcenter/apps/kopano-meet/compose
touch .env

# ask if running with self signed (untrusted) certificates
update_env_file INSECURE $(ucr get kopano/docker/INSECURE)
