#!/bin/bash
VERSION=1

. /usr/share/univention-join/joinscripthelper.lib
. /usr/share/univention-appcenter/joinscripthelper.sh
. /usr/share/univention-lib/ldap.sh
. /usr/share/univention-lib/base.sh

joinscript_init
eval "$(ucr shell)"

random_string() {
        LC_CTYPE=C tr -dc 'a-zA-Z0-9' < /dev/urandom | head -c32
}

update_env_file () {
    varname="$1"
    varvalue="$2"
    if ! grep -q "$varname" ./.env; then
        echo "$varname=$varvalue" >> ./.env
    else
        sed -i "/$varname/c $varname=$varvalue" ./.env
    fi
}

# just add setting if it does not yet exist
add_env_file () {
    varname="$1"
    varvalue="$2"
    if ! grep -q "$varname" ./.env; then
        echo "$varname=$varvalue" >> ./.env
    fi
}

# register Konnect at the Univention OpenID Provider
clientsecret=$(random_string)
fqdn="$hostname.$domainname"
udm oidc/rpservice create --ignore_exists \
 --set name=kopano-meet \
 --position=cn=oidc,cn=univention,$(ucr get ldap/base) \
 --set clientid=kopanoid \
 --set clientsecret=$clientsecret \
 --set trusted=yes \
 --set applicationtype=web \
 --set redirectURI=https://$fqdn/kopanoid/

# restart openid provider for registration to take effect
systemctl restart docker-app-openid-connect-provider.service

cd /var/lib/univention-appcenter/apps/kopano-meet/compose
touch .env

add_env_file clientsecret $clientsecret

# restart containers for changes to take effect
docker-compose up -d

joinscript_save_current_version
exit 0
